export const ADD_EVENT_TYPES = 'ADD_EVENT_TYPES';
export const ADD_EVENT_TYPE = 'ADD_EVENT_TYPE';
export const EVENT_TYPE_ERROR = 'EVENT_TYPE_ERROR';
export const SHOW_EVENT_TYPE = 'SHOW_EVENT_TYPE';
export const REMOVE_EVENT_TYPE = 'REMOVE_EVENT_TYPE';
