export const ADD_LOCATION_TYPES = 'ADD_LOCATION_TYPES';
export const ADD_LOCATION_TYPE = 'ADD_LOCATION_TYPE';
export const LOCATION_TYPE_ERROR = 'LOCATION_TYPE_ERROR';
export const SHOW_LOCATION_TYPE = 'SHOW_LOCATION_TYPE';
export const REMOVE_LOCATION_TYPE = 'REMOVE_LOCATION_TYPE';
