export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const SHOW_LOCATION = 'SHOW_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
