export const ADD_PAYMENT_METHODS = 'ADD_PAYMENT_METHODS';
export const ADD_PAYMENT_HISTORY = 'ADD_PAYMENT_HISTORY';
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD';
export const PAYMENT_METHOD_ERROR = 'PAYMENT_METHOD_ERROR';
export const SHOW_PAYMENT_METHOD = 'SHOW_PAYMENT_METHOD';
export const REMOVE_PAYMENT_METHOD = 'REMOVE_PAYMENT_METHOD';
