export const ADD_PROMO_CODES = 'ADD_PROMO_CODES';
export const ADD_PROMO_CODE = 'ADD_PROMO_CODE';
export const PROMO_CODE_ERROR = 'PROMO_CODE_ERROR';
export const SHOW_PROMO_CODE = 'SHOW_PROMO_CODE';
export const REMOVE_PROMO_CODE = 'REMOVE_PROMO_CODE';
