export const ADD_SPECIALS = 'ADD_SPECIALS';
export const ADD_SPECIAL = 'ADD_SPECIAL';
export const SPECIAL_ERROR = 'SPECIAL_ERROR';
export const SHOW_SPECIAL = 'SHOW_SPECIAL';
export const REMOVE_SPECIAL = 'REMOVE_SPECIAL';
